apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Repository ${{ values.name }} created by Backstage
  tags:
    - java
    - spring-boot
spec:
  type: service
  lifecycle: experimental
  owner: user:development/guest
