apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.componentName }}
  description: ${{ values.description }}
  annotations:
    gitlab.com/project-slug: ${{ values.repoUrl | parseRepoUrl | pick('owner') }}/${{ values.componentName }}
    jenkins.io/job-full-name: ${{ values.componentName }}
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  language: ${{ values.language }}
